version: '3.9'

services:
  web:
    container_name: web
    build:
      context: .
      dockerfile: apps/docker/web/Dockerfile
    volumes:
      - static:/app/web/static

    ports:
      - 8000:8000

    env_file:
      - ./.env.dev
    
    depends_on:
      - db

  db:
    image: postgres:15
    volumes:
      - postgres_data:/var/lib/postgresql/data/
    environment:
      - POSTGRES_USER=hello_django
      - POSTGRES_PASSWORD=hello_django
      - POSTGRES_DB=hello_django_dev

  www:
    container_name: www
    build:
      context: .
      dockerfile: apps/docker/www/Dockerfile
    volumes:
      - node_modules:/app/www/node_modules
    ports:
      - 3000:3000
  
  nginx:
    container_name: nginx
    build:
      context: .
      dockerfile: apps/docker/nginx/Dockerfile
    volumes:
      - static:/app/web/static
    ports:
      - 80:80


volumes:
  static:
  node_modules:
  postgres_data: