version: '3.8'

services:
  front-end:
    container_name: front-end
    build:
      context: .
      dockerfile: docker/front-end/Dockerfile
    volumes:
      - node_modules:/code/front-end/node_modules
    ports:
      - 3000:3000
  nginx:
    container_name: nginx
    build:
      context: .
      dockerfile: docker/nginx/Dockerfile
    volumes:
      - static:/code/static
    ports:
      - 80:80
  web:
    build: .
    command: gunicorn traceable_ledger.wsgi:application --bind 0.0.0.0:8000
    volumes:
      - .:/code
    ports:
      - "8000:8000"
    environment:
      - DEBUG=0
      - DATABASE_URL=postgres://user:password@db:5432/dbname
    depends_on:
      - db
  db:
    image: postgres:13
    volumes:
      - postgres_data:/var/lib/postgresql/data/
    environment:
      - POSTGRES_USER=user
      - POSTGRES_PASSWORD=password
      - POSTGRES_DB=dbname

volumes:
  postgres_data:
  static:
  node_modules:
